server:
  port: 8888
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog
    username: blog_user
    password: blog_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true